### PR TITLE
chore: delete .github/workflows/semgrep.yml

### PR DESCRIPTION
**Pull request by chmccreery**
This repository was still using semgrep-action, which calls semgrep 1.36.0, but we are deprecating that version of semgrep.

Let's take this opportunity to remove the CI config entirely and just use Semgrep Managed Scanning instead!

### Security

- [ ] Change has no security implications (otherwise, ping the security team)

### CODE REVIEW

**Comment by aryx** [comment]
haha, we are the worst :)

**Review by aryx — APPROVED** [review]
would be good to replace with a good one.

**Comment by chmccreery** [comment]
> would be good to replace with a good one.

I'm enabling SMS for it! SMS is the future!

**Comment by aryx** [comment]
excellent!

**Pull request merged**
